; PlatformIO Project Configuration File
; Sniffer_Teensy_V1 — Teensy 4.1 16-ch logic capture
; Docs: https://docs.platformio.org/en/latest/projectconf/index.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
monitor_raw = yes
build_flags =
    -DF_CPU=600000000
    -DUSB_SERIAL
    -O2
    -Wall
    -Wextra
    -Iinclude
build_src_filter = +<*>
lib_deps =
    ; no external deps for Phase 1
